[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects if you add a backend later
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend.vercel.app/api/:splat"
#   status = 200