// Focus dashboard data — Supabase-backed. Reads the Focus-ORE window from the
// daily-task tables (the same tables DailyTaskTracker uses) and today's persisted
// AI brief from focus_briefs. The AI text is GENERATED by the nightly edge
// function (PR2); the dashboard only READS it here.

import { create } from 'zustand';
import { subDays, format } from 'date-fns';
import { supabase } from '../../lib/supabase';
import { useSupabaseAuthStore } from '../../store/supabaseAuthStore';
import { computeMetrics, type FocusMetrics } from './focusLogic';
import { charter, type FocusDay } from './sampleData';

const userId = () => useSupabaseAuthStore.getState().user?.id ?? null;

function toHours(value: unknown): number {
  const n = parseFloat(String(value ?? '').replace(/[^0-9.]/g, ''));
  return Number.isFinite(n) ? n : 0;
}

interface FocusBrief {
  analysis: string | null;
  focus: string | null;
  model: string | null;
}

interface FocusDataStore {
  metrics: FocusMetrics | null;
  brief: FocusBrief | null;
  oreConfigured: boolean;
  loading: boolean;
  initialized: boolean;
  error: string | null;
  init: () => Promise<void>;
}

export const useFocusDataStore = create<FocusDataStore>((set) => ({
  metrics: null,
  brief: null,
  oreConfigured: true,
  loading: false,
  initialized: false,
  error: null,

  init: async () => {
    const uid = userId();
    if (!uid) return set({ error: 'Not authenticated', initialized: true });
    set({ loading: true, error: null });
    const now = new Date();

    // 1) find the Focus ORE (a custom_task whose name matches the charter)
    const { data: oreRows } = await supabase
      .from('custom_tasks')
      .select('id, name')
      .eq('new_user_id', uid)
      .eq('name', charter.focusOreName)
      .limit(1);
    const ore = oreRows?.[0];
    if (!ore) {
      return set({ oreConfigured: false, loading: false, initialized: true, metrics: computeMetrics([], 7, now) });
    }

    // 2) the 7-day window of dates (offset 0 = today … 6)
    const dates: { offset: number; str: string }[] = [];
    for (let offset = 0; offset < 7; offset++) dates.push({ offset, str: format(subDays(now, offset), 'yyyy-MM-dd') });
    const dateStrs = dates.map((d) => d.str);

    // 3) completions (the hours) + per-day notes for the Focus ORE in the window
    const [{ data: comps }, { data: notes }] = await Promise.all([
      supabase
        .from('daily_task_completions')
        .select('completion_date, value')
        .eq('new_user_id', uid)
        .eq('custom_task_id', ore.id)
        .in('completion_date', dateStrs),
      supabase
        .from('daily_task_notes')
        .select('note_date, note_text')
        .eq('new_user_id', uid)
        .eq('custom_task_id', ore.id)
        .in('note_date', dateStrs),
    ]);

    const compByDate = new Map((comps ?? []).map((c: { completion_date: string; value: unknown }) => [c.completion_date, c.value]));
    const noteByDate = new Map((notes ?? []).map((n: { note_date: string; note_text: string }) => [n.note_date, n.note_text]));

    const focusDays: FocusDay[] = dates.map(({ offset, str }) => ({
      offset,
      hours: compByDate.has(str) ? toHours(compByDate.get(str)) : 0,
      note: noteByDate.get(str) || undefined,
    }));

    // 4) today's persisted brief
    const { data: briefRow } = await supabase
      .from('focus_briefs')
      .select('analysis_text, focus_text, model')
      .eq('new_user_id', uid)
      .eq('brief_date', format(now, 'yyyy-MM-dd'))
      .maybeSingle();

    set({
      metrics: computeMetrics(focusDays, 7, now),
      brief: briefRow
        ? { analysis: briefRow.analysis_text ?? null, focus: briefRow.focus_text ?? null, model: briefRow.model ?? null }
        : null,
      oreConfigured: true,
      loading: false,
      initialized: true,
    });
  },
}));
