// Focus dashboard data — Supabase-backed. Reads the Focus-ORE window from the
// daily-task tables (the same tables DailyTaskTracker uses) and today's persisted
// AI brief from focus_briefs. The AI text is GENERATED by the nightly edge
// function (PR2); the dashboard only READS it here.

import { create } from 'zustand';
import { subDays, format } from 'date-fns';
import { supabase } from '../../lib/supabase';
import { useSupabaseAuthStore } from '../../store/supabaseAuthStore';
import { computeMetrics, computeWeekStats, type FocusMetrics, type WeekStats } from './focusLogic';
import { type FocusDay } from './sampleData';
import { parseCharter, normalizeName, DEFAULT_CHARTER, type CharterConfig } from './charterConfig';

const userId = () => useSupabaseAuthStore.getState().user?.id ?? null;

function toHours(value: unknown): number {
  const n = parseFloat(String(value ?? '').replace(/[^0-9.]/g, ''));
  return Number.isFinite(n) ? n : 0;
}

interface FocusBrief {
  analysis: string | null;
  focus: string | null;
  model: string | null;
}

// One fetch covers every surface: the 7-day strip, the Mon-Sun week (which needs
// last week too), and the 3-month trend. 98 days = 14 whole weeks, so the 3m
// chart's oldest weekly bucket is always complete rather than a partial stub.
const HISTORY_DAYS = 98;

interface FocusDataStore {
  metrics: FocusMetrics | null;
  week: WeekStats | null;
  days: FocusDay[];
  brief: FocusBrief | null;
  config: CharterConfig;
  oreConfigured: boolean;
  availableOres: string[];
  loading: boolean;
  initialized: boolean;
  error: string | null;
  init: () => Promise<void>;
}

export const useFocusDataStore = create<FocusDataStore>((set) => ({
  metrics: null,
  week: null,
  days: [],
  brief: null,
  config: DEFAULT_CHARTER,
  oreConfigured: true,
  availableOres: [],
  loading: false,
  initialized: false,
  error: null,

  init: async () => {
    const uid = userId();
    if (!uid) return set({ error: 'Not authenticated', initialized: true });
    set({ loading: true, error: null });
    const now = new Date();

    // 0) read this user's Charter page and parse their config (ORE name, tag,
    //    goal, unit). Falls back to DEFAULT_CHARTER when unset.
    const { data: charterRow } = await supabase
      .from('kb_documents')
      .select('content')
      .eq('new_user_id', uid)
      .eq('metadata->>role', 'charter')
      .maybeSingle();
    const config = parseCharter(charterRow?.content);

    // 1) find the Focus ORE — the custom_task whose name matches the charter.
    //    Matched client-side on the user's own task list (a dozen rows at most)
    //    rather than with a SQL `ilike`: task names are free text and routinely
    //    carry stray whitespace ("Hard Focus Hours ") that HTML collapses, so an
    //    exact server-side comparison silently misses the row the user can see.
    const { data: taskRows } = await supabase
      .from('custom_tasks')
      .select('id, name')
      .eq('new_user_id', uid);
    const tasks = (taskRows ?? []) as { id: string; name: string }[];
    const target = normalizeName(config.focusOreName);
    const ore = tasks.find((t) => normalizeName(t.name) === target);
    if (!ore) {
      return set({
        config,
        oreConfigured: false,
        availableOres: tasks.map((t) => t.name.trim()).filter(Boolean),
        loading: false,
        initialized: true,
        metrics: computeMetrics([], 7, now, config.weeklyAverageGoal),
        week: computeWeekStats([], now, config.weeklyAverageGoal),
        days: [],
      });
    }

    // 2) the history window of dates (offset 0 = today … HISTORY_DAYS-1)
    const dates: { offset: number; str: string }[] = [];
    for (let offset = 0; offset < HISTORY_DAYS; offset++) dates.push({ offset, str: format(subDays(now, offset), 'yyyy-MM-dd') });
    const dateStrs = dates.map((d) => d.str);

    // 3) completions (the hours) + per-day notes for the Focus ORE in the window
    const [{ data: comps }, { data: notes }] = await Promise.all([
      supabase
        .from('daily_task_completions')
        .select('completion_date, value')
        .eq('new_user_id', uid)
        .eq('custom_task_id', ore.id)
        .in('completion_date', dateStrs),
      supabase
        .from('daily_task_notes')
        .select('note_date, note_text')
        .eq('new_user_id', uid)
        .eq('custom_task_id', ore.id)
        .in('note_date', dateStrs.slice(0, 7)), // notes only surface on the 7-day strip
    ]);

    const compByDate = new Map((comps ?? []).map((c: { completion_date: string; value: unknown }) => [c.completion_date, c.value]));
    const noteByDate = new Map((notes ?? []).map((n: { note_date: string; note_text: string }) => [n.note_date, n.note_text]));

    const focusDays: FocusDay[] = dates.map(({ offset, str }) => ({
      offset,
      hours: compByDate.has(str) ? toHours(compByDate.get(str)) : 0,
      note: noteByDate.get(str) || undefined,
    }));

    // 4) today's persisted brief
    const { data: briefRow } = await supabase
      .from('focus_briefs')
      .select('analysis_text, focus_text, model')
      .eq('new_user_id', uid)
      .eq('brief_date', format(now, 'yyyy-MM-dd'))
      .maybeSingle();

    set({
      metrics: computeMetrics(focusDays, 7, now, config.weeklyAverageGoal),
      week: computeWeekStats(focusDays, now, config.weeklyAverageGoal),
      days: focusDays,
      // surface the ORE's own stored name, so the dashboard title reads exactly
      // like the task card the user already knows (minus the stray whitespace)
      config: { ...config, focusOreName: ore.name.trim() },
      brief: briefRow
        ? { analysis: briefRow.analysis_text ?? null, focus: briefRow.focus_text ?? null, model: briefRow.model ?? null }
        : null,
      oreConfigured: true,
      availableOres: tasks.map((t) => t.name.trim()).filter(Boolean),
      loading: false,
      initialized: true,
    });
  },
}));
